export enum ErrorCode {
  DEVICE_CAPACITY_REQUIRED = 'DEVICE_CAPACITY_REQUIRED',
  DEVICE_CAPACITY_ZERO = 'DEVICE_CAPACITY_ZERO',
  DEVICE_CAPACITY_NEGATIVE = 'DEVICE_CAPACITY_NEGATIVE',
  DEVICE_CAPACITY_OUT_OF_RANGE = 'DEVICE_CAPACITY_OUT_OF_RANGE',
  DEVICE_NAME_EMPTY = 'DEVICE_NAME_EMPTY',
  DEVICE_TYPE_REQUIRED = 'DEVICE_TYPE_REQUIRED',
  DEVICE_ALREADY_EXISTS = 'DEVICE_ALREADY_EXISTS',
  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',

  ENERGY_VALUE_REQUIRED = 'ENERGY_VALUE_REQUIRED',
  ENERGY_UNIT_REQUIRED = 'ENERGY_UNIT_REQUIRED',
  ENERGY_NEGATIVE = 'ENERGY_NEGATIVE',

  PRODUCTION_RATE_EXCEEDED = 'PRODUCTION_RATE_EXCEEDED',

  BUILDING_NAME_EMPTY = 'BUILDING_NAME_EMPTY',
  BUILDING_ADDRESS_EMPTY = 'BUILDING_ADDRESS_EMPTY',
  BUILDING_ALREADY_EXISTS = 'BUILDING_ALREADY_EXISTS',
  BUILDING_NOT_FOUND = 'BUILDING_NOT_FOUND',
}
